### ISSUE TITLE
":" in filenames under benchmarks

### ISSUE THREAD

**Issue by jacopol** [imitator-model-checker/imitator#68]
Several filenames in benchmark directory contain the character ":" which results in an illegal file name under Windows.
As a result, the imitator repository cannot be checked out under Windows.
Example: 
`error: invalid path 'benchmarks/ATM/fig1-DCLXZL18:fixed.imi'`

**Comment by DylanMarinho** [comment]
Fixed by commit 2845b2d.

"-" is now used instead of ":" in file names and previous "-" are replaced by "_"
