### ISSUE TITLE
Add modulo function

### ISSUE THREAD

**Issue by lbinria** [imitator-model-checker/imitator#72]
## Goal

We can use `mod(x, i)` functions on arithmetic expressions.

## Finish

 - No parsing error
 - We can use `mod(x, i)` function in inits / constant declarations / guards / invariants / updates / conditionals
 -  `mod(x, i)` function behavior is correct
 - Type checking is make and correct
 - Non regression tests created and succeed

**Comment by etienneandre** [comment]
seems to be implemented as of the current version on develop
